#!/usr/bin/python3

from random import randint, choice
from os import listdir

ROOT = "/"

def get_files():
	pass

def italian():
	pass

[print("get raviolid"), ] if randint(1,6) == 6 else print("fine")
